SHOW DATABASES;
USE world;
SHOW TABLES;

/*
EL COMANDO SELECT SIRVE PARA SELECCIONAR AQUELLO QUE QUERAMOS VISUALIZAR
SINTAXIS: SELECT COLUMNA/S FROM TABLA;
*/
SELECT * FROM city; -- SELECCIONA TODAS LAS COLUMNAS DE LA TABLA CITY