SHOW DATABASES;
USE world;
SHOW TABLES;

/*
EL COMANDO SELECT SIRVE PARA SELECCIONAR AQUELLO QUE QUERAMOS VISUALIZAR
SINTAXIS: SELECT COLUMNA/S FROM TABLA;
*/
SELECT * FROM city; -- SELECCIONA TODAS LAS COLUMNAS DE LA TABLA CITY
SELECT * FROM city 
LIMIT 50; -- LIMIT ENSEÑA EL NUMERO DE COLUMNAS QUE LE INDIQUEMOS

SELECT CountryCode, District FROM city; -- TAMBIÉN PODEMOS SELECCIONAR LAS COLUMNAS CONCRETAS QUE QUERAMOS VER, NOS LAS ENSEÑARÁ EL EN EL ORDEN EL QUE LAS ESCRIBAMOS

SELECT 4+5; -- MySQL PERMITE HACER OPERACIONES SOBRE LA MARCHA UTILIZANDO LAS EXPRESIONES. 
SELECT 4+5 FROM dual; -- OTRA MANERA DE HACER UNA OPERACION SOBRE LA MARCHA

SELECT Name, Population*2 FROM city; -- PODEMOS HACER OPERACIONES CON LAS COLUMNAS DE LAS TABLAS 
SELECT Name, Population*2 AS "DoublePopulation" FROM city; -- USANDO LA PALABRA "AS" PODEMOS ASIGNARLE ALIAS A UNA COLUMNA O UNA EXPRESION
/*SE RECOMIENDA QUE LOS NOMBRES DE POBLACIONES VAYAN ENTRE COMILLAS, O AL MENOS SIN ESPACIOS*/

SELECT 4+5*10; -- EL ORDEN OPERACIONAL ES EL NORMAL EN LAS OPERACIONES MATEMÁTICAS

SELECT DISTINCT CountryCode FROM city; -- LA PALABRA DISTINC, ELIMINA LAS REPETICIONES EN LOS RESULTADOS
SELECT DISTINCT CountryCode, Language FROM countrylanguage;

use CONQUERBLOCKS; 

SELECT NAME, ID FROM world.city; -- SEPARANDO EL NOMBRE DE LA TABLA CON EL NOMBRE DE LA DB PODEMOS REFERENCIAR LA BASE DE DATOS QUE QUERAMOS PARA ASEGURAR QUE ESTAMOS
								 -- UTILIZANDO LA TABLA CORRECTA EN LA BASE CORRECTA 