-- == CLASE AMA SOBRE SUBCONSULTAS, Y REPASO GENERAL == 
-- CUANDO OBSERVAMOS QUE CON UN SELECT NORMAL, NO PODEMOS CONSEGUIR LA INFORMACIÓN QUE NOS SOLICITAN, ES CUANDO TENEMOS QUE HACER UNA SUBCONSULTA O UNA UNION DE TABLA
 
 -- REPASO DE EJERCICIOS SUBCONSULTAS FROM
 -- 1. TABLA academia USAR UNA SUBCONSULTA EN EL FROM PARA DEVOLVER LOS CURSOS ENTRE 1 Y 5. VISUALIZAR EL NUMERO DE ALUMNOS EN CADA CURSO. 
SELECT NOMBRE FROM CURSOS WHERE COD_CURSO IN (1,2,3,4,5);
SELECT COD_CURSO, COUNT(*) AS NUM_ALUMNOS FROM ALUMNOS GROUP BY COD_CURSO;

SELECT CURSOS.NOMBRE, COUNT(ALUMNOS.COD_CURSO) AS NUMERO_ALUMNOS
FROM (SELECT * FROM CURSOS WHERE COD_CURSO BETWEEN 1 AND 5)
AS CURSOS INNER JOIN ALUMNOS ON ALUMNOS.COD_CURSO =  CURSOS.COD_CURSO
GROUP BY CURSOS.NOMBRE;

-- 2.USAR SUBCONSULTA EN EL FROM PARA DEVOLVER LOS PROFESORES Y EL NUMERO DE ASIGNATURAS QUE IMPARTEN. LUEGO VISUALIZA SOLO LOS QUE TENGAN MÁS DE 3 ASIGNATURAS
SELECT * FROM(
    SELECT PROFESORES.COD_PROFESOR, PROFESORES.NOMBRE, COUNT(ASIGNATURAS.NOMBRE) AS NUM_ASIGNATURAS
	FROM PROFESORES INNER JOIN ASIGNATURAS ON PROFESORES.COD_PROFESOR = ASIGNATURAS.COD_PROFESOR
    GROUP BY PROFESORES.COD_PROFESOR) AS T WHERE NUM_ASIGNATURAS > 3;
    
-- REPASO DE EJERCICIOS SUBCONSULTAS WHERE
-- 3. ALUMNOS DE INFORMÁTICA QUE TENGAN UNA NOTA MAYOR QUE LA MEDIA DE LA ASIGNATURA. (DEBERIAN SALIR TODOS LOS DE MÁS DE 5.9 QUE ES LA NOTA MEDIA)
SELECT * FROM ALUMNOS INNER JOIN NOTAS_ALUMNOS INNER JOIN ASIGNATURAS
ON ALUMNOS.cod_alumno = NOTAS_ALUMNOS.cod_alumno AND NOTAS_ALUMNOS.cod_asignatura = ASIGNATURAS.cod_asignatura
WHERE ASIGNATURAS.nombre = "informatica" 
AND NOTAS_ALUMNOS.nota > (SELECT AVG(nota) FROM ASIGNATURAS INNER JOIN NOTAS_ALUMNOS ON NOTAS_ALUMNOS.cod_asignatura = ASIGNATURAS.cod_asignatura
WHERE ASIGNATURAS.nombre = "informatica");
