/*== CROSS JOINS ==*/
-- RELACIONA TODAS LAS TABLAS DE LA PRIMERA TABLA CON LAS DE LA SEGUNDA TABLA. SI POR EJEMPLO TENEMOS UNA TABLA CON 5 FILAS Y OTRA CON 5 FILAS, 
-- AL HACER UNA CROSS JOIN, TENDREMOS UNA TABLA CON 25 FILAS POR QUE LO RELACIONA TODO. 

SELECT DEPARTAMENTOS.nombre, EMPLEADOS.nombre, EMPLEADOS.APELLIDO 
FROM DEPARTAMENTOS CROSS JOIN EMPLEADOS
ORDER BY DEPARTAMENTOS.nombre;

/*EN ESTE EJEMPLO NO TIENE MUCHO SENTIDO POR QUE ESTA RELACIONANDO EMPLEADOS CON DEPARTAMENTOS EN LOS QUE NO ESTÁ.*/