START TRANSACTION ; -- INDICAMOS QUE SE COMIENZA UNA TRANSACCIÓN
DELETE FROM NOTAS_ALUMNOS WHERE cod_alumno > 4;
INSERT INTO ALUMNOS VALUES (900, 'xxxxxxxxx', 'xxxxxxxx', 'xxxxxx@gmail.com', 20, 2);
INSERT INTO NOTAS_ALUMNOS VALUES (900, 2, 1,0);
COMMIT; -- INDICA EL FINAL DE LA TRANSACCIÓN

SELECT * FROM ALUMNOS;

ROLLBACK; -- SI DESPUES DE UN COMMIT, HAGO UN ROLLBACK, NO SE DESHACE ABSOLUTAMENTE NADA.