/*
	DATA MANIPULATION LANGUAGE (DML)
    -1. INSERCIONES, MODIFICACIONES Y BORRADOS
    -2. COMANDOS MAS COMPLEJOS: REPLACE, MERGE
    -3. CONCEPTO DE TRANSACCION - CONJUNTO DE OPERACIONES QUE DEBEN HACERSE TODAS JUNTAS
    -4. COMANDOS DE TRANSACCIONES
*/

USE DML;

/*INSERT -- INSERTA FILAS

INSERT  INTO TABLA (C1, C2) VALUES (V1,V2)
*/

INSERT INTO ESTUDIANTES (CODIGO, NOMBRE, EDAD, FECHA_MATRICULA) VALUES (1, 'JUAN', 23, '2024-01-25');
INSERT INTO ESTUDIANTES (CODIGO, NOMBRE, EDAD, FECHA_MATRICULA) VALUES (2, 'MARIA', 20, '2024-01-26');
-- Si se respeta el orden nativo de las columnas y se rellenan todos los datos, no es necesario poner las columnas
INSERT INTO ESTUDIANTES VALUES (3, 'PACO', 30, '2024-01-30'); 
-- Otra cosa que se puede hacer es cambiar el orden de las columnas, si se cambia el orden de los valores
INSERT INTO ESTUDIANTES (NOMBRE, FECHA_MATRICULA, CODIGO, EDAD) VALUES ('PEDRO', '2024-01-11', 4, 26);

-- Cuando una columna tiene permitido ser null, o tiene un valor por defecto, podemos obviar esa columna
INSERT INTO ESTUDIANTES (CODIGO, NOMBRE, EDAD, FECHA_MATRICULA) VALUES (5, 'ALEJANDRO','2024-01-25');
-- En caso contrario devolverá error
INSERT INTO ESTUDIANTES (CODIGO, NOMBRE, EDAD, FECHA_MATRICULA) VALUES (6, 23, '2024-01-25');
-- También podemos fozar que sea null aunque tenga un valor por defecto
INSERT INTO ESTUDIANTES (CODIGO, NOMBRE, EDAD, FECHA_MATRICULA) VALUES (6, 'SERGIO', NULL, '2024-01-25');

/*INSERT MULTIPLES*/
INSERT INTO ESTUDIANTES (CODIGO, NOMBRE, EDAD, FECHA_MATRICULA) VALUES 
(7, 'ROSA', 24, '2024-01-12'),
(8, 'MARIA', 26, '2024-01-08'),
(9, 'LUIS', 30, '2024-01-15');

-- OTRA FORMA MENOS UTILIZADA DE HACER INSERT MULTIPLES ES INTRODUCIRLA DESDE OTRA TABLA, PUDIENDO HACERLO CON UNA SELECT NORMAL Y CORRIENTE

INSERT INTO ALUMNOS SELECT * FROM ESTUDIANTES WHERE EDAD IS NOT NULL;

SELECT * FROM ESTUDIANTES;
SELECT * FROM ALUMNOS;
