-- EJERCICIOS TABLAS Y CONSTRAINS
-- 1. Dentro de la base de datos acaldemia crea la siguiente tabla: 
use academia; 
CREATE TABLE SERVIDORES(
COD_SERVIDOR INT, 
NOMBRE VARCHAR(50),
MARCA VARCHAR(50),
MEMORIA INT, 
DISCO INT,
PRECIO DECIMAL(5,2), 
CPUs INT,
FECHA_COMPRA DATE);

-- 2. AÑADIR UNA COLUMNA NUEVA LLAMADA DESCUENTO
ALTER TABLE SERVIDORES ADD DESCUENTO INT;

-- 3. INSERTAR UN PAR DE FILAS A LA TABLA
INSERT INTO SERVIDORES (COD_SERVIDOR, NOMBRE, MARCA, MEMORIA, DISCO, PRECIO, CPUs, FECHA_COMPRA) VALUES (1, 'SERVER1', 'MARCA1', 5, 500, 499.50, 4, '2025-03-10');
INSERT INTO SERVIDORES (COD_SERVIDOR, NOMBRE, MARCA, MEMORIA, DISCO, PRECIO, CPUs, FECHA_COMPRA) VALUES (2, 'SERVER2', 'MARCA2', 10, 1024, 999, 8, '2025-03-10');

-- 4. MODIFICAR DESCUENTO A VARCHAR(2); 
ALTER TABLE SERVIDORES MODIFY DESCUENTO VARCHAR(2);

-- 5.MODIFICAR DE NUEVO A INT
ALTER TABLE SERVIDORES MODIFY DESCUENTO INT;

-- 6.MODIFICAR MARCA PARA CONVERTIRLA A INT
ALTER TABLE SERVIDORES MODIFY MARCA INT; -- error por que el tipo de dato no es compatible

-- 7. MODIFICAR LONGITUD DE UNA COLUMNA A UN VALOR MENOR
ALTER TABLE SERVIDORES MODIFY MARCA VARCHAR(30);

-- 8. CAMBIAR POSICION COLUMNA DESCUENTO PARA QUE APAREZCA DESPUES PRECIO
ALTER TABLE SERVIDORES MODIFY 




DESC SERVIDORES;