-- EJERCICIOS TABLAS Y CONSTRAINS
-- 1. Dentro de la base de datos acaldemia crea la siguiente tabla: 
use academia; 
CREATE TABLE SERVIDORES(
COD_SERVIDOR INT, 
NOMBRE VARCHAR(50),
MARCA VARCHAR(50),
MEMORIA INT, 
DISCO INT,
PRECIO DECIMAL(5,2), 
CPUs INT,
FECHA_COMPRA DATE);

-- 2. AÑADIR UNA COLUMNA NUEVA LLAMADA DESCUENTO
ALTER TABLE SERVIDORES ADD DESCUENTO INT;

-- 3. INSERTAR UN PAR DE FILAS A LA TABLA
INSERT INTO SERVIDORES (COD_SERVIDOR, NOMBRE, MARCA, MEMORIA, DISCO, PRECIO, CPUs, FECHA_COMPRA) VALUES (1, 'SERVER1', 'MARCA1', 5, 500, 499.50, 4, '2025-03-10');
INSERT INTO SERVIDORES (COD_SERVIDOR, NOMBRE, MARCA, MEMORIA, DISCO, PRECIO, CPUs, FECHA_COMPRA) VALUES (2, 'SERVER2', 'MARCA2', 10, 1024, 999, 8, '2025-03-10');

-- 4. MODIFICAR DESCUENTO A VARCHAR(2); 
ALTER TABLE SERVIDORES MODIFY DESCUENTO VARCHAR(2);

-- 5.MODIFICAR DE NUEVO A INT
ALTER TABLE SERVIDORES MODIFY DESCUENTO INT;

-- 6.MODIFICAR MARCA PARA CONVERTIRLA A INT
ALTER TABLE SERVIDORES MODIFY MARCA INT; -- error por que el tipo de dato no es compatible

-- 7. MODIFICAR LONGITUD DE UNA COLUMNA A UN VALOR MENOR
ALTER TABLE SERVIDORES MODIFY MARCA VARCHAR(30);

-- 8. CAMBIAR POSICION COLUMNA DESCUENTO PARA QUE APAREZCA DESPUES PRECIO
ALTER TABLE SERVIDORES MODIFY DESCUENTO INT AFTER PRECIO;

-- 9. MODIFICAR AL MISMO TIEMPO MARCA Y MODELO A VARCHAR(75) Y PONER MARCA ANTES QUE COD SERVIDOR;
ALTER TABLE SERVIDORES MODIFY MARCA VARCHAR(75) FIRST,
					   MODIFY NOMBRE VARCHAR(75);
-- 10. MODIFICAR EL NOMBRE DE LA COLUMNA DISCO A ALMACENAMIENTO
ALTER TABLE SERVIDORES CHANGE COLUMN DISCO ALMACENAMIENTO VARCHAR(75);
                       
-- 11. BORRAR COLUMNA FECHA COMPLA
ALTER TABLE SERVIDORES DROP FECHA_COMPRA;

-- 12. CREA UNA COLUMNA LLAMADA PRECIO_SERVIDOR QUE CONTENTA EL PRECIO DEL SERVIDOR MENOS EL DESCUENTO
ALTER TABLE SERVIDORES ADD PRECIO_SERVIDOR DECIMAL GENERATED ALWAYS AS (PRECIO - ((PRECIO * DESCUENTO)/100));

-- 13. INSERTA FILA PARA VER EL RESULTADO
INSERT INTO SERVIDORES (COD_SERVIDOR, NOMBRE, MARCA, MEMORIA, ALMACENAMIENTO, PRECIO, CPUs, DESCUENTO) VALUES ('5', 'SERVER5', 'MARCA5', 8, 500, 100, 2,25);

-- 14. CREA OTRA COLUMNA GENERADA QUE DEVUELVE EL NOMBRE Y LA MARCA CONCATENADA, DEBE LLAMARSE DATOS_SERVIDOR.
ALTER TABLE SERVIDORES ADD DATOS_SERVIDOR VARCHAR(100) GENERATED ALWAYS AS (CONCAT(NOMBRE," ",MARCA));
-- 15. INSERTA FILA PARA VER EL RESULTADO
INSERT INTO SERVIDORES (COD_SERVIDOR, NOMBRE, MARCA, MEMORIA, ALMACENAMIENTO, PRECIO, CPUs, DESCUENTO) VALUES ('7', 'SERVER7', 'MARCA7', 12, 500, 200, 12,25);

-- 16. RENOMBRA LA TABLA CREADA
RENAME TABLE SERVIDORES TO academia.SERVIDOR;

-- 17. MUEVE LA BASE DE DATOS A OTRA TABLA Y COMPRUEBA QUE HA FUNCIONADO
RENAME TABLE SERVIDOR TO DML.SERVIDOR;

-- 18. BORRA LA TABLA QUE ACABAS DE CREAR
DROP TABLE DML.SERVIDOR;





SELECT * FROM SERVIDORES;

DESC SERVIDORES;