-- SAVE POINTS -> ROLLBACKS PARCIALES -> NOS PERMITEN GUARDAR HASTA CIERTO PUNTO
START TRANSACTION;
	DELETE FROM NOTAS_ALUMNOS WHERE COD_ALUMNO = 900;
	INSERT INTO ALUMNOS VALUES (999, 'XXXXX', 'XXXXX', 'xxxxx@gmail.com', 20,2);
    INSERT INTO NOTAS_ALUMNOS VALUES (999, 2,1,0);
    
    SAVEPOINT PASO2;
    
    UPDATE ALUMNOS SET APELLIDOS = "PRUEBA";
    
        
SELECT * FROM ALUMNOS; 

ROLLBACK TO PASO2; -- ESTE ROLLBACK PUEDE HACERSE BIEN TODO, BIEN DEL SAVEPOINT