-- TRUNCATE -> SE PARECE A DELETE, PERO DELETE ES UN COMANDO TRANSACCIONAL. ESTO QUIERE DECIR QUE SI HACEMOS UN DELETE Y LUEGO HACEMOS UN ROLLBACK, RECUPERAMOS LA TABLA
-- PERO TRUNCATE, PRIMERO BORRA LA TABLA ENTERA Y DESPUES LA VUELVE A CREAR. POR LO TANTO LOS DATOS QUE BORREMOS CON TRUNCATE NO SE PUEDEN RECUPERAR CON UN ROLLBACK. 


USE DML;
SELECT * FROM ESTUDIANTES; 

TRUNCATE ESTUDIANTES;
ROLLBACK; 