/*ACTUALIZACIONES DE BASES DE DATOS (UPDATE)

UPDATE - MODIFICA / ACTUALIZA VALORES DE UNA TABLA

UPDATE TABLE
	SET COL1 = VALOR, COL2 = VAL.....
    WHERE CONDICION

*/

SELECT * FROM ESTUDIANTES;

UPDATE ESTUDIANTES
	SET NOMBRE = 'JUAN LUIS' WHERE CODIGO = 1;
    
UPDATE ESTUDIANTES
	SET EDAD = 40 WHERE FECHA_MATRICULA = "2024-01-11"; 
    
-- --------------------------------------------------------------
    
/*BORRAR REGISTROS DE LA TABLA (DELETE)
	
    DELETE FROM TABLA WHERE CONDICION

OJO MUCHO CUIDADO CON ESTO, LA CONDICION NO ES DEL TODO OBLIGATORIO, POR LO TANTO, SI NO LO PONEMOS O LO HACEMOS MAL, BORRAREMOS TODA LA TABLA COMPLETA
ES UN ERROR TIPICO Y MUY FACIL DE COMETER SI NO SE TIENE CUIDADO
*/
DELETE FROM ESTUDIANTES WHERE CODIGO = 9;


/*REEMPLAZAR DATOS DE UNA FILA (REPLACE)

REPLACE INTO TABLE (C1, C2) VALUES (VAL1, VAL2);
*/

REPLACE INTO ESTUDIANTES (CODIGO, NOMBRE, EDAD, FECHA_MATRICULA) 
VALUES (6, "MANUEL", 33, "2024-01-14");

REPLACE INTO ESTUDIANTES (CODIGO, NOMBRE, EDAD, FECHA_MATRICULA) 
VALUES (9, "ISMAEL", 28, "2024-01-30"); -- SI LO EJECUTAMOS EN UNA FILA QUE NO EXISTA, SE COMPORTARÁ COMO UN INSERT


