-- == CONSTRAINTS == -- 
/* 
-- Sirven para poner reglas dentro de los datos que vamos a guardar en una tabla
-- Nos permiten guardar la integridad de la información 
-- Existen restricciones a nivel de tabla y a nivel de columna


***** RESTRICCIONES MÁS HABITUALES *****
- NOT NULL -> Impide tener un valor nulo en un campo
- PRIMARY KEY -> Impide que haya valores duplicados y tampoco soporta nulos
- UNIQUE -> Impide que haya valores duplicados en un campo
- FOREIGN KEY -> Relaciona unas tablas con otras para que no se rompa la integridad entre ellas
- CHECK -> Condición que ha de cumplirse dentro de una columna
- DEFAULT -> Permite poner un valor por defecto en una columna
*/

CREATE SCHEMA RESTRICCIONES;
USE RESTRICCIONES; 

-- NOT NULL --
-- IMPIDE QUE HAYA NULOS
CREATE TABLE TABLA1(
CODIGO INT NOT NULL, 
NOMBRE VARCHAR(50));

DESC TABLA1;

INSERT INTO TABLA1(CODIGO) VALUES(10);
INSERT INTO TABLA1(NOMBRE) VALUES("JUAN"); -- ERROR POR QUE CODIGO NO PUEDE SER NULO

SELECT * FROM TABLA1;

-- PRIMARY KEY --
-- NO PUEDE SER NI NULO NI DUPLICADO
	-- NATURAL: CLAVES QUE EXISTEN NARUALMENTE, POR EJEMPLO: DNI, MATRICULA, COD_PRODUCTO
    -- SUBROGADAS: CLAVES QUE NOS INVENTAMOS, POR EJEMPLO: COD_ALUMNO, COD_DEPTO. 
CREATE TABLE TABLA2(
CODIGO INT PRIMARY KEY, 
NOMBRE VARCHAR(50));

DESC TABLA2;

INSERT INTO TABLA2(CODIGO, NOMBRE) VALUES(1, "JUAN");
INSERT INTO TABLA2(CODIGO, NOMBRE) VALUES(1, "JUAN"); -- ERROR POR QUE NO PUEDE HABER VALORES DUPLICADOS

CREATE TABLE TABLA3(
COD_ALUMNO INT AUTO_INCREMENT PRIMARY KEY, -- CON AUTO INCREMENT, LA COLUMNA SE GENERA SOLA SUMANDO A UNO CADA VEZ, POR DEFECTO EMPIEZA EN 1
NOMBRE_ALUMNO VARCHAR(50) );

INSERT INTO TABLA3(NOMBRE_ALUMNO) VALUES ("ALBERTO");
INSERT INTO TABLA3(NOMBRE_ALUMNO) VALUES ("MARIA");
SELECT * FROM TABLA3;

CREATE TABLE TABLA4(
COD_ALUMNO INT AUTO_INCREMENT PRIMARY KEY, 
NOMBRE_ALUMNO VARCHAR(50) );

ALTER TABLE TABLA4 AUTO_INCREMENT = 100; -- PARA DECIR DESDE DONDE EMPIEZA AUTO INCREMENTE
INSERT INTO TABLA4(NOMBRE_ALUMNO) VALUES ("ALBERTO");
INSERT INTO TABLA4(NOMBRE_ALUMNO) VALUES ("SOFIA");
SELECT * FROM TABLA4;

-- CONSTRAINTS A NIVEL DE TABLA
-- SE PUEDE DAR EL CASO DE QUE POR EJEMPLO TENGAMOS DOS PRODUCTOS CON EL MISMO CODIGO PERO CON UN PROVEEDOR DIFERENTE. PARA ESTE CASO, LO QUE PODEMOS HACER ES 
-- DEFINIRLO A NIVEL DE TABLA, Y ESTABLECER DOS COLUMNAS COMO CLAVE PRIMARIA, COMO EN EL EJEMPLO A CONTINUACION. SI SOLO PUSIERAMOS UNA COLUMNA, FUNCIONARIA
-- IGUAL QUE SI FUERA A NIVEL DE COLUMNA. 
CREATE TABLE TABLA5(
CODIGO INT, 
COD_PROVEEDOR INT,
PRODUCTO VARCHAR(50),
PRIMARY KEY (CODIGO, COD_PROVEEDOR) -- DE ESTA MANERA LA CLAVE PRIMARA SON DOS CAMPOS, EN EL ORDEN EN EL QUE LO HEMOS DEFINIDO
);

DESC TABLA5;

INSERT INTO TABLA5 (CODIGO, COD_PROVEEDOR, PRODUCTO) VALUES (1, 003, "TIJERAS");
INSERT INTO TABLA5 (CODIGO, COD_PROVEEDOR, PRODUCTO) VALUES (1, 004, "LAPICES");
SELECT * FROM TABLA5;

-- UNIQUE -- 
-- ES IGUAL QUE PRIMARY KEY, CON LA DIFERENCIA DE QUE SI PERMITE QUE HAYA NULOS
CREATE TABLE TABLA6 (
COD_EMPLEADO INT PRIMARY KEY, 
DNI VARCHAR (30) UNIQUE, 
NOMBRE VARCHAR (50)
);

INSERT INTO TABLA6 VALUES (1, "123456A", "JUAN");
INSERT INTO TABLA6 VALUES (2, "123456A", "MARIA"); -- ERROR POR QUE EL CAMPO DNI ESTA DUPLICADO
INSERT INTO TABLA6 VALUES (3, "678901J", "MARIO");
INSERT INTO TABLA6 VALUES (2, NULL, "MARIA");

SELECT * FROM TABLA6;

-- DEFAULT -- 
-- PERMITE PONER UN VALOR POR DEFECTO A UNA COLUMNA
CREATE TABLE ALUMNOS_DEFAULT(
CODIGO INT PRIMARY KEY, 
PAIS VARCHAR(50) NOT NULL DEFAULT ("ESPAÑA"),
FECHA_ALTA DATE NOT NULL DEFAULT(curdate()));

INSERT INTO ALUMNOS_DEFAULT (CODIGO) VALUES(1);
INSERT INTO ALUMNOS_DEFAULT (CODIGO, PAIS) VALUES (2, "MEXICO");
INSERT INTO ALUMNOS_DEFAULT (CODIGO, FECHA_ALTA) VALUES (3, curdate());
SELECT * FROM ALUMNOS_DEFAULT;

-- CHECK -- 
-- SIRVE PARA ESTABLECER UNA CONDICION QUE TIENE QUE CUMPLIRSE 
 
CREATE TABLE CLIENTES_CHECK(
CODIGO INT PRIMARY KEY, 
NOMBRE VARCHAR(50),
EDAD INT,
FECHA_ALTA DATE NOT NULL DEFAULT(curdate()),
CONSTRAINT CHECK (EDAD>18)
);

INSERT INTO CLIENTES_CHECK VALUES (1, "PACO", 50, "2023-01-01");
INSERT INTO CLIENTES_CHECK VALUES (2, "JUAN", 17, "2023-01-01"); -- ERROR POR QUE ES MENOR DE 18

-- LA DIFERENCIA ENTRE HACERLO A NIVEL DE COLUMNA Y A NIVEL DE TABLA, ES QUE DE LA PRIMERA FORMA SOLO AFECTAMOS A LA COLUMNA Y DE LA OTRA FORMA PODEMOS
-- SER MAS FLEXIBLES Y AÑADIR MAS DE UNA RESTRICCION

CREATE TABLE COMPRAS_CLIENTES(
COD_CLIENTE INT PRIMARY KEY,
NOMBRE VARCHAR(50),
EDAD INT CHECK(EDAD>18), 
FECHA_COMPRA DATE NOT NULL DEFAULT(current_date()),
FECHA_PAGO DATE, CONSTRAINT CHECK(FECHA_PAGO > FECHA_COMPRA)
);


INSERT INTO COMPRAS_CLIENTES VALUES (1, "PACO", 40, "2024-3-05", current_date());
INSERT INTO COMPRAS_CLIENTES VALUES (2, "LUCIA", 40, "2024-03-05", "2024-03-01"); 
