-- == INFORMATION_SCHEMA == --
/*
-- EXISTE UNA BASE DE DATOS DENTRO DE MYSQL QUE ES UNA BASE DE DATOS PROPIA, QUE NOS PERMITE RECUPERAR INFORMACIÓN DE LOS METADATOS DE LAS TABLAS
-- PODEMOS CONSULTAR INFORMACIÓN DE UNA TABLA EN ESPECIFICO QUE HAYAMOS UTILIZANDO ANTES
-- ES IMPORTANTE PONER A QUE BASE DE DATOS PERTENECE LA TABLA PARA CONSULTAR MEJOR LA INFO
-- TAMBIEN ES IMPORTANTE PONERLE NOMBRE A LAS RESTRICCIONES PARA QUE SEA MAS FACIL TRABAJAR CON ELLAS.

*/

SHOW DATABASES; -- PARA VER TODAS LAS BASES DE DATOS DENTRO DE MYSQL (CREADAS Y LAS QUE VIENEN POR DEFECTO)

use information_schema;
show tables;

desc information_schema.tables;

select * from information_schema.tables where table_schema = "world" and table_name="country";

-- ***** VER LAS CONSTRAINTS DE UNA TABLA DESDE INFORMATION SCHEMA *****
select * from information_schema.table_constraints where table_schema = "RESTRICCIONES" and table_name = "PEDIDOS";

USE RESTRICCIONES;

CREATE TABLE EJEMPLO(
CODIGO INT PRIMARY KEY, 
PROVINCIA VARCHAR(50),
FECHA DATE, 
FECHA_PAGO DATE, 
NOMBRE VARCHAR(100) CONSTRAINT CHECK_NOMBRE CHECK(LENGTH(NOMBRE)>2),
CONSTRAINT CHECK_FECHAS CHECK (FECHA_PAGO > FECHA)
);

SHOW CREATE TABLE EJEMPLO;
SELECT * FROM information_schema.table_constraints WHERE table_name = 'EJEMPLO' and table_schema = "RESTRICCIONES";

DROP TABLE EJEMPLO; 

-- ** AÑADIR CONSTRAINTS A UNA TABLA YA CREADA **** 
-- HAY QUE TENER EN CUENTA, QUE NO SE PUEDEN MODIFICAR RESTRICCIONES YA CREADAS. PERO SI QUE SE PUEDE BORRAR LA RESTRICCION Y DESPUES AÑADIR UNA RESTRICCION NUEVA
-- PARA AÑADIR UNA RESTRICCION -> ALTER TABLE TABLA ADD CONSTRAINT
-- PARA BORRAR UNA RESTRICCION -> ALTER TABLE TABLA DROP CONSTRAINT

CREATE TABLE EJEMPLO(
CODIGO INT, 
PROVINCIA VARCHAR(50),
FECHA DATE, 
FECHA_PAGO DATE, 
NOMBRE VARCHAR(100)
);

ALTER TABLE EJEMPLO ADD CONSTRAINT CLAVE PRIMARY KEY(CODIGO); -- AÑADIENDO UNA CONSTRAINT PRIMARY KEY
ALTER TABLE EJEMPLO ADD CONSTRAINT CHECK1 CHECK (LENGTH(NOMBRE) > 2); -- AÑADIENDO UNA COSNTRAINT DE TIPO CHECK 
ALTER TABLE EJEMPLO ADD CONSTRAINT CHECK2 CHECK (FECHA_PAGO > FECHA);

DESC EJEMPLO;

-- PARA AÑADIR DEFAULT Y NOT NULL, HAY QUE HACERLO DE MANERA DIFERENTE, POR QUE NO SE LES CONSIDERA RESTRICCIONES COMO TAL

ALTER TABLE EJEMPLO MODIFY PROVINCIA VARCHAR(20) NOT NULL; -- AÑADIENDO UN NOT NULL
ALTER TABLE EJEMPLO MODIFY PROVINCIA VARCHAR(50) NULL; -- QUITANDO LA CONSTRAINT ANTERIOR

ALTER TABLE EJEMPLO ALTER PROVINCIA SET DEFAULT 'CACERES'; -- AÑADIENDO VALOR POR DEFECTOA A UNA COLUMNA

ALTER TABLE EJEMPLO DROP CONSTRAINT CHECK2; -- BORRANDO UNA CONSTRAINT
ALTER TABLE CLIENTES DROP PRIMARY KEY; -- NO PODEMOS BORRARLA POR QUE TIENE UNA TABLA HIJA QUE DEPENDE DE ESTA CLAVE PRIMARIA. 




