-- == RENOMBRADO Y BORRADO DE VISTAS == -- 

RENAME TABLE VISTA TO VISTA_NUEVA; -- RENOMBRANDO UNA VISTA

SELECT * FROM VISTA_NUEVA;

DROP VIEW VISTA_NUEVA; -- ELIMINANDO UNA VISTA
DROP VIEW IF EXISTS VISTA_NUEVA; -- EL IF EXISTS VIENE BIEN PONERLO POR SI NO EXISTE LA VISTA, QUE NO SE DETENGA LA EJECUCIÓN